apiVersion: apps/v1
kind: Deployment
metadata:
  name: miw-customerwebapp-deployment
  labels:
    app: miw-customerwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miw-customerwebapp
  template:
    metadata:
      labels:
        app: miw-customerwebapp
    spec:
      containers:
      - name: miw-customerwebapp
        image: docker.io/lars14/miw-customerwebapp:release0.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80