
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miw-customerauthservice
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: miw-customerauthservice-pod 
  template:
    metadata:
      labels:
        app: miw-customerauthservice-pod
    spec:
      containers:
        - name: miw-customerauthservice-container
          image: docker.io/lars14/miw-customerauthservice:release0.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: miw-customerauthservice
spec: 
  selector:
    app: miw-customerauthservice-pod
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: miw-customerauthservice-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: miw-customerauthservice
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
