apiVersion: apps/v1
kind: Deployment
metadata:
  name: miw-customergateway
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: miw-customergateway-pod
      version: latest   
  template:
    metadata:
      labels:
        app: miw-customergateway-pod
        version: latest
    spec:
      containers:
        - name: miw-customergateway-container
          image: docker.io/lars14/miw-customergateway:release0.0.8
          imagePullPolicy: Always
          envFrom:
          #  - secretRef:
          #      name: auth-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: miw-customergateway
  labels:
    app: miw-customergateway
    service: miw-customergateway
spec: 
  selector:
    app: miw-customergateway-pod
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: LoadBalancer  
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: miw-customergateway-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: miw-customergateway
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
