apiVersion: apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miw-customerwebapp
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: miw-customerwebapp-pod
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: miw-customerwebapp-pod
        tier: frontend
        track: stable
    spec:
      containers:
        - name: miw-customerwebapp-container
          image: docker.io/lars14/miw-customerwebapp:release0.0.7
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: miw-customergateway
  labels:
    app: miw-customergateway
    service: miw-customergateway
spec: 
  selector:
    app: miw-customergateway-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: miw-customerwebapp-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: miw-customerwebapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  
